### PR TITLE
Require first and last name input upon registration

### LINKED ISSUE #205: New users can register without name input
When registering as a new user, the Name fields are not required in order to submit the form and create an account. This creates errors in displaying the user's name for their notes and for identifying users.

To reproduce this issue, navigate to register for a new account from the Login page and click the Sign Up button before completing the Name fields.

### PR DESCRIPTION
**Pull request by sesheppard**
Fixes #205

The first and last name input fields on the registration page are now required to be completed in order for the form to be submitted.

An oversight which allows new users to register without entering a first or last name was identified previously. This change makes it so that these fields cannot be left empty, bringing the desktop version of this project in line with the mobile app.

Simple validation functions have been added to validation.js for the first and last name variables in the signupPage's page.tsx file, making it so that the registration request cannot be sent from the client if these fields are left empty. A message prompts the user in the same way as for an invalid E-mail or password in this case. These functions, along with the existing validations for the E-mail and password, can be changed in the future to use more strict rules for the input provided by users.

firstNameMessage
lastNameMessage

### CODE REVIEW

File: app/lib/utils/validation.js [hunk 1]
```diff
@@ -17,3 +17,21 @@ export const validatePassword = (password) => {
   // Add more password validations as needed
   return true;
 };
+
+
+//Only checks if there is at least one character in each field. Can be changed in the future.
+export const validateFirstName = (firstName) => {
```
Comment (amychen108) [inline app/lib/utils/validation.js:23]: This looks good for making sure that the user entry for first name isn't empty. And if it is it'll give them an error to provide one.

File: app/lib/utils/validation.js [hunk 2]
```diff
@@ -17,3 +17,21 @@ export const validatePassword = (password) => {
...
+  if (firstName.length == 0) {
+    toast.error("Must provide a first name");
+    return false;
+  }
+  return true;
+};
+
+export const validateLastName = (lastName) => {
```
Comment (amychen108) [inline app/lib/utils/validation.js:31]: Same as my comment for first name, it makes sure that last name isn't empty and throws an error if it is.
